### ISSUE TITLE
Using model on own data set. 

### ISSUE THREAD

**Issue by yuanzhou15** [NVIDIA/vid2vid#50]
Hi this is an extremely interesting project, I have another set of data set that I would like to use. The data I want to use are images that are taken in 15 minute increments and I want to transform them into another image. We have used pix2pix for this problem set, but we also wanted to see if vid2vid will yield better results.
I want to know how I need to have the images to be formatted or organized before training on them? 
Any help would be much appreciated.

**Comment by tcwang0509** [comment]
You can take a look at the provided example dataset. You dataset should be in the same format.

**Comment by yuanzhou15** [comment]
I tried looking into the example data sets. Would I have the same architecture if I want a image to image transformation? Would i just need Train_A, Train_B and then Test_A and Test_B, and then I just need to specify data-root?

**Comment by tcwang0509** [comment]
If you just want image-to-image translation instead of videos, you can just use this repo: https://github.com/NVIDIA/pix2pixHD/

**Comment by yuanzhou15** [comment]
We are currently using pix2pix as well, but want to see if vid2vid will yield better results since our pictures are a sequence of images. I saw that in the sample data sets, there are more than just .png file. I haven't got a chance to run vid2vid yet, but will we be able to run vid2vid with just train_A and train_B folders with just pictures?

**Comment by tcwang0509** [comment]
Yes, make sure the images in the two folders are in corresponding order (i.e. first image in train_A corresponds to first image in train_B), and it should work.

**Comment by ChristopherLu** [comment]
Also try to see if I can run vid2vid on my own dataset. Are the sequence sub-folders (e.g., seq0001 for cityscapes dataset) necessary? Or I can simply group all image sequences under the train_A folder?

**Comment by kartikJ-9** [comment]
> I tried looking into the example data sets. Would I have the same architecture if I want a image to image transformation? Would i just need Train_A, Train_B and then Test_A and Test_B, and then I just need to specify data-root?

I am trying to replicate the results of the pose model. I trained the model on colab. I have a sequence of images and openpose keypoints JSON file corresponding to each frame, that I need to provide to get the generated video for my use case... But I don't see Train_A,Train_B folders. Since I am trying it in colab, the .py PyTorch variables wont be accessible from colab command line. Please help me here. Thanks in advance.

**Comment by songyn95** [comment]
@tcwang0509  @yuanzhou15 
 At present, I am also doing image to image translation. I have tried pix2pix and pix2pixHD, but since my image is a continuous video frame, I also want to try the vid2vid method. I want to ask the following questions:
1. what is the test effect of this method?
2. The`continue_ train`  command seems to be unavailable.  It needs to be retrained every time. Have you ever encountered this?
3. if `use_real_img` command is used, the first frame is In folder test_B? Must the number of images in folder test_B correspond to that in folder test_A?

Looking forward to your reply!!!
